// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5u2UTRr7ObBrlO_mUTDUpx_RvY2qMVE4',
    appId: '1:737646867874:web:36faefa1d193c009f0eefb',
    messagingSenderId: '737646867874',
    projectId: 'studymedical',
    authDomain: 'studymedical.firebaseapp.com',
    storageBucket: 'studymedical.firebasestorage.app',
    measurementId: 'G-7NCDPS9595',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSRJBBbqfrhjF8vLWhrokCqrkeniDgvnM',
    appId: '1:737646867874:android:b3dd1c0cf39cf78ff0eefb',
    messagingSenderId: '737646867874',
    projectId: 'studymedical',
    storageBucket: 'studymedical.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZTDIegLoxrj25l5DP_qMWjt2YLAb6sRc',
    appId: '1:737646867874:ios:85cac7e17e9da332f0eefb',
    messagingSenderId: '737646867874',
    projectId: 'studymedical',
    storageBucket: 'studymedical.firebasestorage.app',
    iosBundleId: 'com.example.studyMedical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZTDIegLoxrj25l5DP_qMWjt2YLAb6sRc',
    appId: '1:737646867874:ios:85cac7e17e9da332f0eefb',
    messagingSenderId: '737646867874',
    projectId: 'studymedical',
    storageBucket: 'studymedical.firebasestorage.app',
    iosBundleId: 'com.example.studyMedical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5u2UTRr7ObBrlO_mUTDUpx_RvY2qMVE4',
    appId: '1:737646867874:web:1349dbab406c8434f0eefb',
    messagingSenderId: '737646867874',
    projectId: 'studymedical',
    authDomain: 'studymedical.firebaseapp.com',
    storageBucket: 'studymedical.firebasestorage.app',
    measurementId: 'G-Y0KJ3H02JM',
  );
}
